[package]
name = "apply_if"
version = "1.0.0"
license = "MIT OR Apache-2.0"
description = "Conditionally apply a closure to an item or return it"
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
